before_script:
  - wget -O /tmp/dartsdk.zip http://storage.googleapis.com/dart-archive/channels/stable/release/latest/sdk/dartsdk-linux-x64-release.zip
  - unzip /tmp/dartsdk.zip /tmp
  - export DART_SDK=/tmp/dart-sdk
  - export PATH=$DART_SDK/bin:$PATH
script:
 - dartanalyzer web/hasreon_dart.dart